name: Download, Unzip, and Move

on:
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: "Trisplus"  # Replace with your actual name
  GIT_AUTHOR_EMAIL: "trischand@protonmail.com"  # Replace with your email
  ZIP_URL: "https://objects.githubusercontent.com/github-production-release-asset-2e65be/1663468/915a6e40-995a-4901-9193-e0c0390b2f1e?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240731%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240731T101802Z&X-Amz-Expires=300&X-Amz-Signature=8ca425c338aec65110b8c46e6d1f42acbec64e59e09a2e370aef366c2d3068d6&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1663468&response-content-disposition=attachment%3B%20filename%3Dpdfjs-4.5.136-dist.zip&response-content-type=application%2Foctet-stream"  # Replace with the actual URL

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create pdfjs folder
        run: mkdir pdfjs

      - name: Download zip file
        run: curl -L -o pdfjs.zip ${{ env.ZIP_URL }}

      - name: Unzip to pdfjs folder
        run: unzip pdfjs.zip -d pdfjs

      - name: Set Git config
        run: |
          git config --local user.name "${{ env.GIT_AUTHOR_NAME }}"
          git config --local user.email "${{ env.GIT_AUTHOR_EMAIL }}"

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Downloaded and unzipped file to pdfjs folder"

      - name: Push changes
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.AIR_TOKEN }}
