name: Download, Unpack, and Move

on:
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: "Trisplus"  # Replace with your actual name
  GIT_AUTHOR_EMAIL: "trischand@protonmail.com"  # Replace with your email
  TGZ_URL: "https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-4.5.136.tgz"  # Replace with the actual URL

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update and install required packages
        run: |
          sudo apt update
          sudo apt install -y curl tar unzip

      - name: Create pdfjs folder
        run: mkdir pdfjs

      - name: Download tgz file
        run: curl -L -o pdfjs.tgz ${{ env.TGZ_URL }}

      - name: Unpack tgz to pdfjs folder
        run: |
          tar -xzf pdfjs.tgz -C pdfjs
          rm pdfjs.tgz

      - name: Set Git config
        run: |
          git config --local user.name "${{ env.GIT_AUTHOR_NAME }}"
          git config --local user.email "${{ env.GIT_AUTHOR_EMAIL }}"

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Downloaded and unpacked tgz file to pdfjs folder"

      - name: Push changes
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.AIR_TOKEN }}
