name: Unzip pdfjs.zip

on:
  push:
    branches: [ main ]
    paths:
      - 'pdfjs.zip'  # Only trigger on changes to pdfjs.zip

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install unzip -y

      - name: Find and unzip pdfjs.zip
        run: |
          if [[ -f "pdfjs.zip" ]]; then
            unzip pdfjs.zip
          else
            echo "pdfjs.zip not found. Skipping unzip."
          fi

      - name: Check unzip exit code (optional)
        run: |
          if [[ $? -ne 0 ]]; then
            echo "Unzip failed! Check the repository logs for details."
          fi
