name: Unzip, Move, and Commit

on:
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: "Trisplus"  # Replace with your actual name
  GIT_AUTHOR_EMAIL: "trischand@protonmail.com"  # Replace with your email

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install unzip -y

      - name: Create pdfjs folder
        run: mkdir pdfjs

      - name: Find and unzip pdfjs.zip
        run: |
          if [[ -f "pdfjs.zip" ]]; then
            unzip pdfjs.zip -d pdfjs
            rm pdfjs.zip
          else
            echo "pdfjs.zip not found. Skipping unzip."
          fi

      - name: Set Git config
        run: |
          git config --local user.name "${{ env.GIT_AUTHOR_NAME }}"
          git config --local user.email "${{ env.GIT_AUTHOR_EMAIL }}"

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Unzipped and moved files to pdfjs folder"

      - name: Push changes
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.AIR_TOKEN }}
