name: Unzip File

on:
  push:
    branches: [main]
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install unzip -y

      - name: Find zip file
        id: find_zip
        run: |
          find . -name "*.zip" -print -quit

      - name: Unzip file
        if: steps.find_zip.outputs.find_zip != ''
        run: unzip ${{ steps.find_zip.outputs.find_zip }}
