name: Unzip, Delete, and Commit

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install unzip -y

      - name: Find and unzip pdfjs.zip
        run: |
          if [[ -f "pdfjs.zip" ]]; then
            unzip pdfjs.zip
            rm pdfjs.zip
          else
            echo "pdfjs.zip not found. Skipping unzip."
          fi

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Unzipped and deleted pdfjs.zip"

      - name: Push changes
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.AIR_TOKEN }}
